server:
  port: 8989
spring:
  application:
    name: product-service
  cloud:
    config:
      import-check:
        enabled: false
eureka:
  instance:
    metadataMap:
      instanceId: ${spring.application.name}:${server.port}
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

    